modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="hyper_florecent"
version="0.0.2"
displayName="Hyper-florecent"
logoFile="logo.png"
authors="PandaLou & MoltenWolfCub"
description='''
HYPER-FLORECENT ADDS BRIGHT THEMED.                 BLOCKS AND ITEMS!!!!!!!!!!!!!!!!!!!!!!!!
'''

[[dependencies.hyper_florecent]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hyper_florecent]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
